version: '3.3'
services:
  backend:
    build:
      ./backend
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      ./database/postgres
    networks:
      - app-network

  httpd:
    build:
      ./httpd
    ports:
      - 82:80
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network: