---
# tasks file for roles/httpd
- name: Run httpd
  docker_container:
    name: httpd
    image: nicolastvn/tp-devops-cpe-httpd
    ports: 80:80
    state: started
    networks:
      - name: app-network