---
# tasks file for roles/backend
- name: Launch backend
  docker_container:
    name: backend
    image: nicolastvn/tp-devops-cpe-backend
    exposed_ports: 
      - 80:80
    state: started
    networks:
      - name: app-network